In [1]:
from qiskit.quantum_info import Statevector, Operator
import numpy as np

# İzdüşüm operatörü |0><0| ve |1><1|
P0 = np.outer([1, 0], [1, 0])
P1 = np.outer([0, 1], [0, 1])

print("P0 =\n", P0)
print("P1 =\n", P1)
print("P0 + P1 =\n", P0 + P1)   # Tamlık bağıntısı: birim matrise eşit olmalı

# Spektral ayrışım doğrulaması: bir Hermitsel operatörü
# kendi özdeğer/özvektörleriyle yeniden inşa et
Z = np.array([[1, 0], [0, -1]])   # Pauli-Z, Hermitsel bir gözlemlenebilir
eigvals, eigvecs = np.linalg.eigh(Z)
print("Özdeğerler:", eigvals)

reconstructed = sum(eigvals[i] * np.outer(eigvecs[:, i], eigvecs[:, i]) for i in range(2))
print("Yeniden inşa edilen Z =\n", reconstructed)   # orijinal Z ile aynı çıkmalı

P0 =
 [[1 0]
 [0 0]]
P1 =
 [[0 0]
 [0 1]]
P0 + P1 =
 [[1 0]
 [0 1]]
Özdeğerler: [-1.  1.]
Yeniden inşa edilen Z =
 [[ 1.  0.]
 [ 0. -1.]]
